spring:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mariadb://localhost:3306/blog
    username: root
    password: 1234

server:
  port: 8080
